package com.os.manager.dbmodel;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysConfigSettingOptionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public SysConfigSettingOptionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNull() {
            addCriterion("modified_time is null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNotNull() {
            addCriterion("modified_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeEqualTo(Date value) {
            addCriterion("modified_time =", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotEqualTo(Date value) {
            addCriterion("modified_time <>", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThan(Date value) {
            addCriterion("modified_time >", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_time >=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThan(Date value) {
            addCriterion("modified_time <", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThanOrEqualTo(Date value) {
            addCriterion("modified_time <=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIn(List<Date> values) {
            addCriterion("modified_time in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotIn(List<Date> values) {
            addCriterion("modified_time not in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeBetween(Date value1, Date value2) {
            addCriterion("modified_time between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotBetween(Date value1, Date value2) {
            addCriterion("modified_time not between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andSettingTypeIdIsNull() {
            addCriterion("setting_type_id is null");
            return (Criteria) this;
        }

        public Criteria andSettingTypeIdIsNotNull() {
            addCriterion("setting_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andSettingTypeIdEqualTo(Long value) {
            addCriterion("setting_type_id =", value, "settingTypeId");
            return (Criteria) this;
        }

        public Criteria andSettingTypeIdNotEqualTo(Long value) {
            addCriterion("setting_type_id <>", value, "settingTypeId");
            return (Criteria) this;
        }

        public Criteria andSettingTypeIdGreaterThan(Long value) {
            addCriterion("setting_type_id >", value, "settingTypeId");
            return (Criteria) this;
        }

        public Criteria andSettingTypeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("setting_type_id >=", value, "settingTypeId");
            return (Criteria) this;
        }

        public Criteria andSettingTypeIdLessThan(Long value) {
            addCriterion("setting_type_id <", value, "settingTypeId");
            return (Criteria) this;
        }

        public Criteria andSettingTypeIdLessThanOrEqualTo(Long value) {
            addCriterion("setting_type_id <=", value, "settingTypeId");
            return (Criteria) this;
        }

        public Criteria andSettingTypeIdIn(List<Long> values) {
            addCriterion("setting_type_id in", values, "settingTypeId");
            return (Criteria) this;
        }

        public Criteria andSettingTypeIdNotIn(List<Long> values) {
            addCriterion("setting_type_id not in", values, "settingTypeId");
            return (Criteria) this;
        }

        public Criteria andSettingTypeIdBetween(Long value1, Long value2) {
            addCriterion("setting_type_id between", value1, value2, "settingTypeId");
            return (Criteria) this;
        }

        public Criteria andSettingTypeIdNotBetween(Long value1, Long value2) {
            addCriterion("setting_type_id not between", value1, value2, "settingTypeId");
            return (Criteria) this;
        }

        public Criteria andSettingTypeNameIsNull() {
            addCriterion("setting_type_name is null");
            return (Criteria) this;
        }

        public Criteria andSettingTypeNameIsNotNull() {
            addCriterion("setting_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andSettingTypeNameEqualTo(String value) {
            addCriterion("setting_type_name =", value, "settingTypeName");
            return (Criteria) this;
        }

        public Criteria andSettingTypeNameNotEqualTo(String value) {
            addCriterion("setting_type_name <>", value, "settingTypeName");
            return (Criteria) this;
        }

        public Criteria andSettingTypeNameGreaterThan(String value) {
            addCriterion("setting_type_name >", value, "settingTypeName");
            return (Criteria) this;
        }

        public Criteria andSettingTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("setting_type_name >=", value, "settingTypeName");
            return (Criteria) this;
        }

        public Criteria andSettingTypeNameLessThan(String value) {
            addCriterion("setting_type_name <", value, "settingTypeName");
            return (Criteria) this;
        }

        public Criteria andSettingTypeNameLessThanOrEqualTo(String value) {
            addCriterion("setting_type_name <=", value, "settingTypeName");
            return (Criteria) this;
        }

        public Criteria andSettingTypeNameLike(String value) {
            addCriterion("setting_type_name like", value, "settingTypeName");
            return (Criteria) this;
        }

        public Criteria andSettingTypeNameNotLike(String value) {
            addCriterion("setting_type_name not like", value, "settingTypeName");
            return (Criteria) this;
        }

        public Criteria andSettingTypeNameIn(List<String> values) {
            addCriterion("setting_type_name in", values, "settingTypeName");
            return (Criteria) this;
        }

        public Criteria andSettingTypeNameNotIn(List<String> values) {
            addCriterion("setting_type_name not in", values, "settingTypeName");
            return (Criteria) this;
        }

        public Criteria andSettingTypeNameBetween(String value1, String value2) {
            addCriterion("setting_type_name between", value1, value2, "settingTypeName");
            return (Criteria) this;
        }

        public Criteria andSettingTypeNameNotBetween(String value1, String value2) {
            addCriterion("setting_type_name not between", value1, value2, "settingTypeName");
            return (Criteria) this;
        }

        public Criteria andShowIndexIsNull() {
            addCriterion("show_index is null");
            return (Criteria) this;
        }

        public Criteria andShowIndexIsNotNull() {
            addCriterion("show_index is not null");
            return (Criteria) this;
        }

        public Criteria andShowIndexEqualTo(Integer value) {
            addCriterion("show_index =", value, "showIndex");
            return (Criteria) this;
        }

        public Criteria andShowIndexNotEqualTo(Integer value) {
            addCriterion("show_index <>", value, "showIndex");
            return (Criteria) this;
        }

        public Criteria andShowIndexGreaterThan(Integer value) {
            addCriterion("show_index >", value, "showIndex");
            return (Criteria) this;
        }

        public Criteria andShowIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("show_index >=", value, "showIndex");
            return (Criteria) this;
        }

        public Criteria andShowIndexLessThan(Integer value) {
            addCriterion("show_index <", value, "showIndex");
            return (Criteria) this;
        }

        public Criteria andShowIndexLessThanOrEqualTo(Integer value) {
            addCriterion("show_index <=", value, "showIndex");
            return (Criteria) this;
        }

        public Criteria andShowIndexIn(List<Integer> values) {
            addCriterion("show_index in", values, "showIndex");
            return (Criteria) this;
        }

        public Criteria andShowIndexNotIn(List<Integer> values) {
            addCriterion("show_index not in", values, "showIndex");
            return (Criteria) this;
        }

        public Criteria andShowIndexBetween(Integer value1, Integer value2) {
            addCriterion("show_index between", value1, value2, "showIndex");
            return (Criteria) this;
        }

        public Criteria andShowIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("show_index not between", value1, value2, "showIndex");
            return (Criteria) this;
        }

        public Criteria andOptionNameIsNull() {
            addCriterion("option_name is null");
            return (Criteria) this;
        }

        public Criteria andOptionNameIsNotNull() {
            addCriterion("option_name is not null");
            return (Criteria) this;
        }

        public Criteria andOptionNameEqualTo(String value) {
            addCriterion("option_name =", value, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameNotEqualTo(String value) {
            addCriterion("option_name <>", value, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameGreaterThan(String value) {
            addCriterion("option_name >", value, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameGreaterThanOrEqualTo(String value) {
            addCriterion("option_name >=", value, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameLessThan(String value) {
            addCriterion("option_name <", value, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameLessThanOrEqualTo(String value) {
            addCriterion("option_name <=", value, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameLike(String value) {
            addCriterion("option_name like", value, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameNotLike(String value) {
            addCriterion("option_name not like", value, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameIn(List<String> values) {
            addCriterion("option_name in", values, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameNotIn(List<String> values) {
            addCriterion("option_name not in", values, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameBetween(String value1, String value2) {
            addCriterion("option_name between", value1, value2, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionNameNotBetween(String value1, String value2) {
            addCriterion("option_name not between", value1, value2, "optionName");
            return (Criteria) this;
        }

        public Criteria andOptionDescIsNull() {
            addCriterion("option_desc is null");
            return (Criteria) this;
        }

        public Criteria andOptionDescIsNotNull() {
            addCriterion("option_desc is not null");
            return (Criteria) this;
        }

        public Criteria andOptionDescEqualTo(String value) {
            addCriterion("option_desc =", value, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescNotEqualTo(String value) {
            addCriterion("option_desc <>", value, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescGreaterThan(String value) {
            addCriterion("option_desc >", value, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescGreaterThanOrEqualTo(String value) {
            addCriterion("option_desc >=", value, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescLessThan(String value) {
            addCriterion("option_desc <", value, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescLessThanOrEqualTo(String value) {
            addCriterion("option_desc <=", value, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescLike(String value) {
            addCriterion("option_desc like", value, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescNotLike(String value) {
            addCriterion("option_desc not like", value, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescIn(List<String> values) {
            addCriterion("option_desc in", values, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescNotIn(List<String> values) {
            addCriterion("option_desc not in", values, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescBetween(String value1, String value2) {
            addCriterion("option_desc between", value1, value2, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescNotBetween(String value1, String value2) {
            addCriterion("option_desc not between", value1, value2, "optionDesc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated do_not_delete_during_merge Wed Jan 09 13:49:39 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}