package com.os.manager.dbmodel;

import java.util.Date;

public class SysConfigRoles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_roles.id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_roles.create_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_roles.modified_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_roles.role_name
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_roles.role_desc
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private String roleDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_roles.id
     *
     * @return the value of sys_config_roles.id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_roles.id
     *
     * @param id the value for sys_config_roles.id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_roles.create_time
     *
     * @return the value of sys_config_roles.create_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_roles.create_time
     *
     * @param createTime the value for sys_config_roles.create_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_roles.modified_time
     *
     * @return the value of sys_config_roles.modified_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_roles.modified_time
     *
     * @param modifiedTime the value for sys_config_roles.modified_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_roles.role_name
     *
     * @return the value of sys_config_roles.role_name
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_roles.role_name
     *
     * @param roleName the value for sys_config_roles.role_name
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_roles.role_desc
     *
     * @return the value of sys_config_roles.role_desc
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_roles.role_desc
     *
     * @param roleDesc the value for sys_config_roles.role_desc
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc;
    }
}