package com.os.manager.dbmodel;

import java.util.Date;

public class SysConfigRepertory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_repertory.id
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_repertory.create_time
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_repertory.modified_time
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_repertory.repertory_name
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    private String repertoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_repertory.show_index
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    private Integer showIndex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_repertory.id
     *
     * @return the value of sys_config_repertory.id
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_repertory.id
     *
     * @param id the value for sys_config_repertory.id
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_repertory.create_time
     *
     * @return the value of sys_config_repertory.create_time
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_repertory.create_time
     *
     * @param createTime the value for sys_config_repertory.create_time
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_repertory.modified_time
     *
     * @return the value of sys_config_repertory.modified_time
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_repertory.modified_time
     *
     * @param modifiedTime the value for sys_config_repertory.modified_time
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_repertory.repertory_name
     *
     * @return the value of sys_config_repertory.repertory_name
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    public String getRepertoryName() {
        return repertoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_repertory.repertory_name
     *
     * @param repertoryName the value for sys_config_repertory.repertory_name
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    public void setRepertoryName(String repertoryName) {
        this.repertoryName = repertoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_repertory.show_index
     *
     * @return the value of sys_config_repertory.show_index
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    public Integer getShowIndex() {
        return showIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_repertory.show_index
     *
     * @param showIndex the value for sys_config_repertory.show_index
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    public void setShowIndex(Integer showIndex) {
        this.showIndex = showIndex;
    }
}