package com.os.manager.dbmodel;

import java.util.Date;

public class SysConfigSettingOption {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_setting_option.id
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_setting_option.create_time
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_setting_option.modified_time
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_setting_option.setting_type_id
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    private Long settingTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_setting_option.setting_type_name
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    private String settingTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_setting_option.show_index
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    private Integer showIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_setting_option.option_name
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    private String optionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_setting_option.option_desc
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    private String optionDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_setting_option.id
     *
     * @return the value of sys_config_setting_option.id
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_setting_option.id
     *
     * @param id the value for sys_config_setting_option.id
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_setting_option.create_time
     *
     * @return the value of sys_config_setting_option.create_time
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_setting_option.create_time
     *
     * @param createTime the value for sys_config_setting_option.create_time
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_setting_option.modified_time
     *
     * @return the value of sys_config_setting_option.modified_time
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_setting_option.modified_time
     *
     * @param modifiedTime the value for sys_config_setting_option.modified_time
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_setting_option.setting_type_id
     *
     * @return the value of sys_config_setting_option.setting_type_id
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public Long getSettingTypeId() {
        return settingTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_setting_option.setting_type_id
     *
     * @param settingTypeId the value for sys_config_setting_option.setting_type_id
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public void setSettingTypeId(Long settingTypeId) {
        this.settingTypeId = settingTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_setting_option.setting_type_name
     *
     * @return the value of sys_config_setting_option.setting_type_name
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public String getSettingTypeName() {
        return settingTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_setting_option.setting_type_name
     *
     * @param settingTypeName the value for sys_config_setting_option.setting_type_name
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public void setSettingTypeName(String settingTypeName) {
        this.settingTypeName = settingTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_setting_option.show_index
     *
     * @return the value of sys_config_setting_option.show_index
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public Integer getShowIndex() {
        return showIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_setting_option.show_index
     *
     * @param showIndex the value for sys_config_setting_option.show_index
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public void setShowIndex(Integer showIndex) {
        this.showIndex = showIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_setting_option.option_name
     *
     * @return the value of sys_config_setting_option.option_name
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public String getOptionName() {
        return optionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_setting_option.option_name
     *
     * @param optionName the value for sys_config_setting_option.option_name
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public void setOptionName(String optionName) {
        this.optionName = optionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_setting_option.option_desc
     *
     * @return the value of sys_config_setting_option.option_desc
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public String getOptionDesc() {
        return optionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_setting_option.option_desc
     *
     * @param optionDesc the value for sys_config_setting_option.option_desc
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    public void setOptionDesc(String optionDesc) {
        this.optionDesc = optionDesc;
    }
}