package com.os.manager.dbmodel;

import java.util.Date;

public class SysConfigPrice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_price.id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_price.create_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_price.modified_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_price.price_name
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private String priceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_price.price_desc
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private String priceDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_price.show_index
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private Integer showIndex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_price.id
     *
     * @return the value of sys_config_price.id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_price.id
     *
     * @param id the value for sys_config_price.id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_price.create_time
     *
     * @return the value of sys_config_price.create_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_price.create_time
     *
     * @param createTime the value for sys_config_price.create_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_price.modified_time
     *
     * @return the value of sys_config_price.modified_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_price.modified_time
     *
     * @param modifiedTime the value for sys_config_price.modified_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_price.price_name
     *
     * @return the value of sys_config_price.price_name
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public String getPriceName() {
        return priceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_price.price_name
     *
     * @param priceName the value for sys_config_price.price_name
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setPriceName(String priceName) {
        this.priceName = priceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_price.price_desc
     *
     * @return the value of sys_config_price.price_desc
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public String getPriceDesc() {
        return priceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_price.price_desc
     *
     * @param priceDesc the value for sys_config_price.price_desc
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setPriceDesc(String priceDesc) {
        this.priceDesc = priceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_price.show_index
     *
     * @return the value of sys_config_price.show_index
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public Integer getShowIndex() {
        return showIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_price.show_index
     *
     * @param showIndex the value for sys_config_price.show_index
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setShowIndex(Integer showIndex) {
        this.showIndex = showIndex;
    }
}