package com.os.manager.dbmodel;

import java.util.Date;

public class SysManagerSupplier {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier.id
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier.create_time
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier.modified_time
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier.company_name
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier.company_address
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    private String companyAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier.zip_code
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    private String zipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier.company_phone
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    private String companyPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier.company_fax
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    private String companyFax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier.duty_paragraph
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    private String dutyParagraph;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier.opening_bank
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    private String openingBank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier.company_account
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    private String companyAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier.company_website
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    private String companyWebsite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier.company_email
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    private String companyEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier.is_rebate
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    private Boolean isRebate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier.company_desc
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    private String companyDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier.manager_id
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    private String managerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier.id
     *
     * @return the value of sys_manager_supplier.id
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier.id
     *
     * @param id the value for sys_manager_supplier.id
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier.create_time
     *
     * @return the value of sys_manager_supplier.create_time
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier.create_time
     *
     * @param createTime the value for sys_manager_supplier.create_time
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier.modified_time
     *
     * @return the value of sys_manager_supplier.modified_time
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier.modified_time
     *
     * @param modifiedTime the value for sys_manager_supplier.modified_time
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier.company_name
     *
     * @return the value of sys_manager_supplier.company_name
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier.company_name
     *
     * @param companyName the value for sys_manager_supplier.company_name
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier.company_address
     *
     * @return the value of sys_manager_supplier.company_address
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier.company_address
     *
     * @param companyAddress the value for sys_manager_supplier.company_address
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier.zip_code
     *
     * @return the value of sys_manager_supplier.zip_code
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier.zip_code
     *
     * @param zipCode the value for sys_manager_supplier.zip_code
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier.company_phone
     *
     * @return the value of sys_manager_supplier.company_phone
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public String getCompanyPhone() {
        return companyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier.company_phone
     *
     * @param companyPhone the value for sys_manager_supplier.company_phone
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public void setCompanyPhone(String companyPhone) {
        this.companyPhone = companyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier.company_fax
     *
     * @return the value of sys_manager_supplier.company_fax
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public String getCompanyFax() {
        return companyFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier.company_fax
     *
     * @param companyFax the value for sys_manager_supplier.company_fax
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public void setCompanyFax(String companyFax) {
        this.companyFax = companyFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier.duty_paragraph
     *
     * @return the value of sys_manager_supplier.duty_paragraph
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public String getDutyParagraph() {
        return dutyParagraph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier.duty_paragraph
     *
     * @param dutyParagraph the value for sys_manager_supplier.duty_paragraph
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public void setDutyParagraph(String dutyParagraph) {
        this.dutyParagraph = dutyParagraph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier.opening_bank
     *
     * @return the value of sys_manager_supplier.opening_bank
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public String getOpeningBank() {
        return openingBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier.opening_bank
     *
     * @param openingBank the value for sys_manager_supplier.opening_bank
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public void setOpeningBank(String openingBank) {
        this.openingBank = openingBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier.company_account
     *
     * @return the value of sys_manager_supplier.company_account
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public String getCompanyAccount() {
        return companyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier.company_account
     *
     * @param companyAccount the value for sys_manager_supplier.company_account
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public void setCompanyAccount(String companyAccount) {
        this.companyAccount = companyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier.company_website
     *
     * @return the value of sys_manager_supplier.company_website
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public String getCompanyWebsite() {
        return companyWebsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier.company_website
     *
     * @param companyWebsite the value for sys_manager_supplier.company_website
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public void setCompanyWebsite(String companyWebsite) {
        this.companyWebsite = companyWebsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier.company_email
     *
     * @return the value of sys_manager_supplier.company_email
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public String getCompanyEmail() {
        return companyEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier.company_email
     *
     * @param companyEmail the value for sys_manager_supplier.company_email
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public void setCompanyEmail(String companyEmail) {
        this.companyEmail = companyEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier.is_rebate
     *
     * @return the value of sys_manager_supplier.is_rebate
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public Boolean getIsRebate() {
        return isRebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier.is_rebate
     *
     * @param isRebate the value for sys_manager_supplier.is_rebate
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public void setIsRebate(Boolean isRebate) {
        this.isRebate = isRebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier.company_desc
     *
     * @return the value of sys_manager_supplier.company_desc
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public String getCompanyDesc() {
        return companyDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier.company_desc
     *
     * @param companyDesc the value for sys_manager_supplier.company_desc
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public void setCompanyDesc(String companyDesc) {
        this.companyDesc = companyDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier.manager_id
     *
     * @return the value of sys_manager_supplier.manager_id
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier.manager_id
     *
     * @param managerId the value for sys_manager_supplier.manager_id
     *
     * @mbg.generated Fri Jan 11 16:03:09 CST 2019
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }
}