package com.os.manager.dbmodel;

import java.util.Date;

public class SysManagerUserBrand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_user_brand.id
     *
     * @mbg.generated Tue Jan 08 11:46:59 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_user_brand.create_time
     *
     * @mbg.generated Tue Jan 08 11:46:59 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_user_brand.modified_time
     *
     * @mbg.generated Tue Jan 08 11:46:59 CST 2019
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_user_brand.manager_id
     *
     * @mbg.generated Tue Jan 08 11:46:59 CST 2019
     */
    private String managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_user_brand.brand_id
     *
     * @mbg.generated Tue Jan 08 11:46:59 CST 2019
     */
    private Long brandId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_user_brand.id
     *
     * @return the value of sys_manager_user_brand.id
     *
     * @mbg.generated Tue Jan 08 11:46:59 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_user_brand.id
     *
     * @param id the value for sys_manager_user_brand.id
     *
     * @mbg.generated Tue Jan 08 11:46:59 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_user_brand.create_time
     *
     * @return the value of sys_manager_user_brand.create_time
     *
     * @mbg.generated Tue Jan 08 11:46:59 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_user_brand.create_time
     *
     * @param createTime the value for sys_manager_user_brand.create_time
     *
     * @mbg.generated Tue Jan 08 11:46:59 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_user_brand.modified_time
     *
     * @return the value of sys_manager_user_brand.modified_time
     *
     * @mbg.generated Tue Jan 08 11:46:59 CST 2019
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_user_brand.modified_time
     *
     * @param modifiedTime the value for sys_manager_user_brand.modified_time
     *
     * @mbg.generated Tue Jan 08 11:46:59 CST 2019
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_user_brand.manager_id
     *
     * @return the value of sys_manager_user_brand.manager_id
     *
     * @mbg.generated Tue Jan 08 11:46:59 CST 2019
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_user_brand.manager_id
     *
     * @param managerId the value for sys_manager_user_brand.manager_id
     *
     * @mbg.generated Tue Jan 08 11:46:59 CST 2019
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_user_brand.brand_id
     *
     * @return the value of sys_manager_user_brand.brand_id
     *
     * @mbg.generated Tue Jan 08 11:46:59 CST 2019
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_user_brand.brand_id
     *
     * @param brandId the value for sys_manager_user_brand.brand_id
     *
     * @mbg.generated Tue Jan 08 11:46:59 CST 2019
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }
}