
package com.os.manager.dbmodel;

import java.util.Date;

public class SysManagerUser
{
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column sys_manager_user.id
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	private String	id;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column sys_manager_user.create_time
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	private Date	createTime;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column sys_manager_user.modified_time
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	private Date	modifiedTime;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column sys_manager_user.user_name
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	private String	userName;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column sys_manager_user.account_name
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	private String	accountName;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column sys_manager_user.user_phone
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	private String	userPhone;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column sys_manager_user.status
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	private Boolean	status;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column sys_manager_user.area_status
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	private Boolean	areaStatus;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column sys_manager_user.repertory_status
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	private Boolean	repertoryStatus;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column sys_manager_user.brand_status
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	private Boolean	brandStatus;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column sys_manager_user.price_status
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	private Boolean	priceStatus;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column sys_manager_user.password
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	private String	password;

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column sys_manager_user.id
	 *
	 * @return the value of sys_manager_user.id
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public String getId()
	{
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_manager_user.id
	 *
	 * @param id the value for sys_manager_user.id
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public void setId(String id)
	{
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column sys_manager_user.create_time
	 *
	 * @return the value of sys_manager_user.create_time
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public Date getCreateTime()
	{
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_manager_user.create_time
	 *
	 * @param createTime the value for sys_manager_user.create_time
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public void setCreateTime(Date createTime)
	{
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column sys_manager_user.modified_time
	 *
	 * @return the value of sys_manager_user.modified_time
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public Date getModifiedTime()
	{
		return modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_manager_user.modified_time
	 *
	 * @param modifiedTime the value for sys_manager_user.modified_time
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public void setModifiedTime(Date modifiedTime)
	{
		this.modifiedTime = modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column sys_manager_user.user_name
	 *
	 * @return the value of sys_manager_user.user_name
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public String getUserName()
	{
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_manager_user.user_name
	 *
	 * @param userName the value for sys_manager_user.user_name
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public void setUserName(String userName)
	{
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column sys_manager_user.account_name
	 *
	 * @return the value of sys_manager_user.account_name
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public String getAccountName()
	{
		return accountName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_manager_user.account_name
	 *
	 * @param accountName the value for sys_manager_user.account_name
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public void setAccountName(String accountName)
	{
		this.accountName = accountName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column sys_manager_user.user_phone
	 *
	 * @return the value of sys_manager_user.user_phone
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public String getUserPhone()
	{
		return userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_manager_user.user_phone
	 *
	 * @param userPhone the value for sys_manager_user.user_phone
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public void setUserPhone(String userPhone)
	{
		this.userPhone = userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column sys_manager_user.status
	 *
	 * @return the value of sys_manager_user.status
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public Boolean getStatus()
	{
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_manager_user.status
	 *
	 * @param status the value for sys_manager_user.status
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public void setStatus(Boolean status)
	{
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column sys_manager_user.area_status
	 *
	 * @return the value of sys_manager_user.area_status
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public Boolean getAreaStatus()
	{
		return areaStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_manager_user.area_status
	 *
	 * @param areaStatus the value for sys_manager_user.area_status
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public void setAreaStatus(Boolean areaStatus)
	{
		this.areaStatus = areaStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column sys_manager_user.repertory_status
	 *
	 * @return the value of sys_manager_user.repertory_status
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public Boolean getRepertoryStatus()
	{
		return repertoryStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_manager_user.repertory_status
	 *
	 * @param repertoryStatus the value for
	 *        sys_manager_user.repertory_status
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public void setRepertoryStatus(Boolean repertoryStatus)
	{
		this.repertoryStatus = repertoryStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column sys_manager_user.brand_status
	 *
	 * @return the value of sys_manager_user.brand_status
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public Boolean getBrandStatus()
	{
		return brandStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_manager_user.brand_status
	 *
	 * @param brandStatus the value for sys_manager_user.brand_status
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public void setBrandStatus(Boolean brandStatus)
	{
		this.brandStatus = brandStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column sys_manager_user.price_status
	 *
	 * @return the value of sys_manager_user.price_status
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public Boolean getPriceStatus()
	{
		return priceStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_manager_user.price_status
	 *
	 * @param priceStatus the value for sys_manager_user.price_status
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public void setPriceStatus(Boolean priceStatus)
	{
		this.priceStatus = priceStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column sys_manager_user.password
	 *
	 * @return the value of sys_manager_user.password
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public String getPassword()
	{
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_manager_user.password
	 *
	 * @param password the value for sys_manager_user.password
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public void setPassword(String password)
	{
		this.password = password;
	}
}
