
package com.os.manager.dbmodel;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysManagerUserExample
{
	/**
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	protected String	 orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	protected boolean	 distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public SysManagerUserExample()
	{
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public void setOrderByClause(String orderByClause)
	{
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public String getOrderByClause()
	{
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public void setDistinct(boolean distinct)
	{
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public boolean isDistinct()
	{
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public List<Criteria> getOredCriteria()
	{
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public void or(Criteria criteria)
	{
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public Criteria or()
	{
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public Criteria createCriteria()
	{
		Criteria criteria = createCriteriaInternal();
		if(oredCriteria.size() == 0)
		{
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	protected Criteria createCriteriaInternal()
	{
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public void clear()
	{
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds
	 * to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	protected abstract static class GeneratedCriteria
	{
		protected List<Criterion> criteria;

		protected GeneratedCriteria()
		{
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid()
		{
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria()
		{
			return criteria;
		}

		public List<Criterion> getCriteria()
		{
			return criteria;
		}

		protected void addCriterion(String condition)
		{
			if(condition == null)
			{
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition , Object value , String property)
		{
			if(value == null)
			{
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition , Object value1 , Object value2 , String property)
		{
			if(value1 == null || value2 == null)
			{
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull()
		{
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull()
		{
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value)
		{
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value)
		{
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value)
		{
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value)
		{
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value)
		{
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value)
		{
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value)
		{
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value)
		{
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values)
		{
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values)
		{
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1 , String value2)
		{
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1 , String value2)
		{
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull()
		{
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull()
		{
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value)
		{
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value)
		{
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value)
		{
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value)
		{
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value)
		{
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value)
		{
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values)
		{
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values)
		{
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1 , Date value2)
		{
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1 , Date value2)
		{
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeIsNull()
		{
			addCriterion("modified_time is null");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeIsNotNull()
		{
			addCriterion("modified_time is not null");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeEqualTo(Date value)
		{
			addCriterion("modified_time =", value, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeNotEqualTo(Date value)
		{
			addCriterion("modified_time <>", value, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeGreaterThan(Date value)
		{
			addCriterion("modified_time >", value, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeGreaterThanOrEqualTo(Date value)
		{
			addCriterion("modified_time >=", value, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeLessThan(Date value)
		{
			addCriterion("modified_time <", value, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeLessThanOrEqualTo(Date value)
		{
			addCriterion("modified_time <=", value, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeIn(List<Date> values)
		{
			addCriterion("modified_time in", values, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeNotIn(List<Date> values)
		{
			addCriterion("modified_time not in", values, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeBetween(Date value1 , Date value2)
		{
			addCriterion("modified_time between", value1, value2, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeNotBetween(Date value1 , Date value2)
		{
			addCriterion("modified_time not between", value1, value2, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNull()
		{
			addCriterion("user_name is null");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNotNull()
		{
			addCriterion("user_name is not null");
			return (Criteria) this;
		}

		public Criteria andUserNameEqualTo(String value)
		{
			addCriterion("user_name =", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotEqualTo(String value)
		{
			addCriterion("user_name <>", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThan(String value)
		{
			addCriterion("user_name >", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value)
		{
			addCriterion("user_name >=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThan(String value)
		{
			addCriterion("user_name <", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value)
		{
			addCriterion("user_name <=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLike(String value)
		{
			addCriterion("user_name like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotLike(String value)
		{
			addCriterion("user_name not like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameIn(List<String> values)
		{
			addCriterion("user_name in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotIn(List<String> values)
		{
			addCriterion("user_name not in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameBetween(String value1 , String value2)
		{
			addCriterion("user_name between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotBetween(String value1 , String value2)
		{
			addCriterion("user_name not between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andAccountNameIsNull()
		{
			addCriterion("account_name is null");
			return (Criteria) this;
		}

		public Criteria andAccountNameIsNotNull()
		{
			addCriterion("account_name is not null");
			return (Criteria) this;
		}

		public Criteria andAccountNameEqualTo(String value)
		{
			addCriterion("account_name =", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameNotEqualTo(String value)
		{
			addCriterion("account_name <>", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameGreaterThan(String value)
		{
			addCriterion("account_name >", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameGreaterThanOrEqualTo(String value)
		{
			addCriterion("account_name >=", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameLessThan(String value)
		{
			addCriterion("account_name <", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameLessThanOrEqualTo(String value)
		{
			addCriterion("account_name <=", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameLike(String value)
		{
			addCriterion("account_name like", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameNotLike(String value)
		{
			addCriterion("account_name not like", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameIn(List<String> values)
		{
			addCriterion("account_name in", values, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameNotIn(List<String> values)
		{
			addCriterion("account_name not in", values, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameBetween(String value1 , String value2)
		{
			addCriterion("account_name between", value1, value2, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameNotBetween(String value1 , String value2)
		{
			addCriterion("account_name not between", value1, value2, "accountName");
			return (Criteria) this;
		}

		public Criteria andUserPhoneIsNull()
		{
			addCriterion("user_phone is null");
			return (Criteria) this;
		}

		public Criteria andUserPhoneIsNotNull()
		{
			addCriterion("user_phone is not null");
			return (Criteria) this;
		}

		public Criteria andUserPhoneEqualTo(String value)
		{
			addCriterion("user_phone =", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneNotEqualTo(String value)
		{
			addCriterion("user_phone <>", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneGreaterThan(String value)
		{
			addCriterion("user_phone >", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneGreaterThanOrEqualTo(String value)
		{
			addCriterion("user_phone >=", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneLessThan(String value)
		{
			addCriterion("user_phone <", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneLessThanOrEqualTo(String value)
		{
			addCriterion("user_phone <=", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneLike(String value)
		{
			addCriterion("user_phone like", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneNotLike(String value)
		{
			addCriterion("user_phone not like", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneIn(List<String> values)
		{
			addCriterion("user_phone in", values, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneNotIn(List<String> values)
		{
			addCriterion("user_phone not in", values, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneBetween(String value1 , String value2)
		{
			addCriterion("user_phone between", value1, value2, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneNotBetween(String value1 , String value2)
		{
			addCriterion("user_phone not between", value1, value2, "userPhone");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull()
		{
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull()
		{
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Boolean value)
		{
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Boolean value)
		{
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Boolean value)
		{
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Boolean value)
		{
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Boolean value)
		{
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Boolean value)
		{
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Boolean> values)
		{
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Boolean> values)
		{
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Boolean value1 , Boolean value2)
		{
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Boolean value1 , Boolean value2)
		{
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andAreaStatusIsNull()
		{
			addCriterion("area_status is null");
			return (Criteria) this;
		}

		public Criteria andAreaStatusIsNotNull()
		{
			addCriterion("area_status is not null");
			return (Criteria) this;
		}

		public Criteria andAreaStatusEqualTo(Boolean value)
		{
			addCriterion("area_status =", value, "areaStatus");
			return (Criteria) this;
		}

		public Criteria andAreaStatusNotEqualTo(Boolean value)
		{
			addCriterion("area_status <>", value, "areaStatus");
			return (Criteria) this;
		}

		public Criteria andAreaStatusGreaterThan(Boolean value)
		{
			addCriterion("area_status >", value, "areaStatus");
			return (Criteria) this;
		}

		public Criteria andAreaStatusGreaterThanOrEqualTo(Boolean value)
		{
			addCriterion("area_status >=", value, "areaStatus");
			return (Criteria) this;
		}

		public Criteria andAreaStatusLessThan(Boolean value)
		{
			addCriterion("area_status <", value, "areaStatus");
			return (Criteria) this;
		}

		public Criteria andAreaStatusLessThanOrEqualTo(Boolean value)
		{
			addCriterion("area_status <=", value, "areaStatus");
			return (Criteria) this;
		}

		public Criteria andAreaStatusIn(List<Boolean> values)
		{
			addCriterion("area_status in", values, "areaStatus");
			return (Criteria) this;
		}

		public Criteria andAreaStatusNotIn(List<Boolean> values)
		{
			addCriterion("area_status not in", values, "areaStatus");
			return (Criteria) this;
		}

		public Criteria andAreaStatusBetween(Boolean value1 , Boolean value2)
		{
			addCriterion("area_status between", value1, value2, "areaStatus");
			return (Criteria) this;
		}

		public Criteria andAreaStatusNotBetween(Boolean value1 , Boolean value2)
		{
			addCriterion("area_status not between", value1, value2, "areaStatus");
			return (Criteria) this;
		}

		public Criteria andRepertoryStatusIsNull()
		{
			addCriterion("repertory_status is null");
			return (Criteria) this;
		}

		public Criteria andRepertoryStatusIsNotNull()
		{
			addCriterion("repertory_status is not null");
			return (Criteria) this;
		}

		public Criteria andRepertoryStatusEqualTo(Boolean value)
		{
			addCriterion("repertory_status =", value, "repertoryStatus");
			return (Criteria) this;
		}

		public Criteria andRepertoryStatusNotEqualTo(Boolean value)
		{
			addCriterion("repertory_status <>", value, "repertoryStatus");
			return (Criteria) this;
		}

		public Criteria andRepertoryStatusGreaterThan(Boolean value)
		{
			addCriterion("repertory_status >", value, "repertoryStatus");
			return (Criteria) this;
		}

		public Criteria andRepertoryStatusGreaterThanOrEqualTo(Boolean value)
		{
			addCriterion("repertory_status >=", value, "repertoryStatus");
			return (Criteria) this;
		}

		public Criteria andRepertoryStatusLessThan(Boolean value)
		{
			addCriterion("repertory_status <", value, "repertoryStatus");
			return (Criteria) this;
		}

		public Criteria andRepertoryStatusLessThanOrEqualTo(Boolean value)
		{
			addCriterion("repertory_status <=", value, "repertoryStatus");
			return (Criteria) this;
		}

		public Criteria andRepertoryStatusIn(List<Boolean> values)
		{
			addCriterion("repertory_status in", values, "repertoryStatus");
			return (Criteria) this;
		}

		public Criteria andRepertoryStatusNotIn(List<Boolean> values)
		{
			addCriterion("repertory_status not in", values, "repertoryStatus");
			return (Criteria) this;
		}

		public Criteria andRepertoryStatusBetween(Boolean value1 , Boolean value2)
		{
			addCriterion("repertory_status between", value1, value2, "repertoryStatus");
			return (Criteria) this;
		}

		public Criteria andRepertoryStatusNotBetween(Boolean value1 , Boolean value2)
		{
			addCriterion("repertory_status not between", value1, value2, "repertoryStatus");
			return (Criteria) this;
		}

		public Criteria andBrandStatusIsNull()
		{
			addCriterion("brand_status is null");
			return (Criteria) this;
		}

		public Criteria andBrandStatusIsNotNull()
		{
			addCriterion("brand_status is not null");
			return (Criteria) this;
		}

		public Criteria andBrandStatusEqualTo(Boolean value)
		{
			addCriterion("brand_status =", value, "brandStatus");
			return (Criteria) this;
		}

		public Criteria andBrandStatusNotEqualTo(Boolean value)
		{
			addCriterion("brand_status <>", value, "brandStatus");
			return (Criteria) this;
		}

		public Criteria andBrandStatusGreaterThan(Boolean value)
		{
			addCriterion("brand_status >", value, "brandStatus");
			return (Criteria) this;
		}

		public Criteria andBrandStatusGreaterThanOrEqualTo(Boolean value)
		{
			addCriterion("brand_status >=", value, "brandStatus");
			return (Criteria) this;
		}

		public Criteria andBrandStatusLessThan(Boolean value)
		{
			addCriterion("brand_status <", value, "brandStatus");
			return (Criteria) this;
		}

		public Criteria andBrandStatusLessThanOrEqualTo(Boolean value)
		{
			addCriterion("brand_status <=", value, "brandStatus");
			return (Criteria) this;
		}

		public Criteria andBrandStatusIn(List<Boolean> values)
		{
			addCriterion("brand_status in", values, "brandStatus");
			return (Criteria) this;
		}

		public Criteria andBrandStatusNotIn(List<Boolean> values)
		{
			addCriterion("brand_status not in", values, "brandStatus");
			return (Criteria) this;
		}

		public Criteria andBrandStatusBetween(Boolean value1 , Boolean value2)
		{
			addCriterion("brand_status between", value1, value2, "brandStatus");
			return (Criteria) this;
		}

		public Criteria andBrandStatusNotBetween(Boolean value1 , Boolean value2)
		{
			addCriterion("brand_status not between", value1, value2, "brandStatus");
			return (Criteria) this;
		}

		public Criteria andPriceStatusIsNull()
		{
			addCriterion("price_status is null");
			return (Criteria) this;
		}

		public Criteria andPriceStatusIsNotNull()
		{
			addCriterion("price_status is not null");
			return (Criteria) this;
		}

		public Criteria andPriceStatusEqualTo(Boolean value)
		{
			addCriterion("price_status =", value, "priceStatus");
			return (Criteria) this;
		}

		public Criteria andPriceStatusNotEqualTo(Boolean value)
		{
			addCriterion("price_status <>", value, "priceStatus");
			return (Criteria) this;
		}

		public Criteria andPriceStatusGreaterThan(Boolean value)
		{
			addCriterion("price_status >", value, "priceStatus");
			return (Criteria) this;
		}

		public Criteria andPriceStatusGreaterThanOrEqualTo(Boolean value)
		{
			addCriterion("price_status >=", value, "priceStatus");
			return (Criteria) this;
		}

		public Criteria andPriceStatusLessThan(Boolean value)
		{
			addCriterion("price_status <", value, "priceStatus");
			return (Criteria) this;
		}

		public Criteria andPriceStatusLessThanOrEqualTo(Boolean value)
		{
			addCriterion("price_status <=", value, "priceStatus");
			return (Criteria) this;
		}

		public Criteria andPriceStatusIn(List<Boolean> values)
		{
			addCriterion("price_status in", values, "priceStatus");
			return (Criteria) this;
		}

		public Criteria andPriceStatusNotIn(List<Boolean> values)
		{
			addCriterion("price_status not in", values, "priceStatus");
			return (Criteria) this;
		}

		public Criteria andPriceStatusBetween(Boolean value1 , Boolean value2)
		{
			addCriterion("price_status between", value1, value2, "priceStatus");
			return (Criteria) this;
		}

		public Criteria andPriceStatusNotBetween(Boolean value1 , Boolean value2)
		{
			addCriterion("price_status not between", value1, value2, "priceStatus");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull()
		{
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull()
		{
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value)
		{
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value)
		{
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value)
		{
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value)
		{
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value)
		{
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value)
		{
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value)
		{
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value)
		{
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values)
		{
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values)
		{
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1 , String value2)
		{
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1 , String value2)
		{
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds
	 * to the database table sys_manager_user
	 *
	 * @mbg.generated do_not_delete_during_merge Tue Jan 08 09:41:24 CST
	 *                2019
	 */
	public static class Criteria extends GeneratedCriteria
	{
		protected Criteria()
		{
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds
	 * to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	public static class Criterion
	{
		private String	condition;
		private Object	value;
		private Object	secondValue;
		private boolean	noValue;
		private boolean	singleValue;
		private boolean	betweenValue;
		private boolean	listValue;
		private String	typeHandler;

		public String getCondition()
		{
			return condition;
		}

		public Object getValue()
		{
			return value;
		}

		public Object getSecondValue()
		{
			return secondValue;
		}

		public boolean isNoValue()
		{
			return noValue;
		}

		public boolean isSingleValue()
		{
			return singleValue;
		}

		public boolean isBetweenValue()
		{
			return betweenValue;
		}

		public boolean isListValue()
		{
			return listValue;
		}

		public String getTypeHandler()
		{
			return typeHandler;
		}

		protected Criterion(String condition)
		{
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition , Object value , String typeHandler)
		{
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if(value instanceof List<?>)
			{
				this.listValue = true;
			}
			else
			{
				this.singleValue = true;
			}
		}

		protected Criterion(String condition , Object value)
		{
			this(condition, value, null);
		}

		protected Criterion(String condition , Object value , Object secondValue , String typeHandler)
		{
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition , Object value , Object secondValue)
		{
			this(condition, value, secondValue, null);
		}
	}
}
