package com.os.manager.dao;

import com.os.manager.dbmodel.SysConfigRepertory;
import com.os.manager.dbmodel.SysConfigRepertoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysConfigRepertoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_repertory
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    long countByExample(SysConfigRepertoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_repertory
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    int deleteByExample(SysConfigRepertoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_repertory
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_repertory
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    int insert(SysConfigRepertory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_repertory
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    int insertSelective(SysConfigRepertory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_repertory
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    List<SysConfigRepertory> selectByExample(SysConfigRepertoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_repertory
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    SysConfigRepertory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_repertory
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysConfigRepertory record, @Param("example") SysConfigRepertoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_repertory
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    int updateByExample(@Param("record") SysConfigRepertory record, @Param("example") SysConfigRepertoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_repertory
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    int updateByPrimaryKeySelective(SysConfigRepertory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_repertory
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    int updateByPrimaryKey(SysConfigRepertory record);
}