package com.os.manager.dao;

import com.os.manager.dbmodel.SysConfigSetting;
import com.os.manager.dbmodel.SysConfigSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysConfigSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    long countByExample(SysConfigSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    int deleteByExample(SysConfigSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    int insert(SysConfigSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    int insertSelective(SysConfigSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    List<SysConfigSetting> selectByExample(SysConfigSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    SysConfigSetting selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysConfigSetting record, @Param("example") SysConfigSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    int updateByExample(@Param("record") SysConfigSetting record, @Param("example") SysConfigSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    int updateByPrimaryKeySelective(SysConfigSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    int updateByPrimaryKey(SysConfigSetting record);
}