package com.os.manager.dao;

import com.os.manager.dbmodel.SysConfigRoleAuth;
import com.os.manager.dbmodel.SysConfigRoleAuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysConfigRoleAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_role_auth
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    long countByExample(SysConfigRoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_role_auth
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int deleteByExample(SysConfigRoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_role_auth
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_role_auth
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int insert(SysConfigRoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_role_auth
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int insertSelective(SysConfigRoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_role_auth
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    List<SysConfigRoleAuth> selectByExample(SysConfigRoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_role_auth
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    SysConfigRoleAuth selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_role_auth
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysConfigRoleAuth record, @Param("example") SysConfigRoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_role_auth
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int updateByExample(@Param("record") SysConfigRoleAuth record, @Param("example") SysConfigRoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_role_auth
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int updateByPrimaryKeySelective(SysConfigRoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_role_auth
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int updateByPrimaryKey(SysConfigRoleAuth record);
}