package com.os.manager.dao;

import com.os.manager.dbmodel.SysManagerUser;
import com.os.manager.dbmodel.SysManagerUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysManagerUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_user
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    long countByExample(SysManagerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_user
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int deleteByExample(SysManagerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_user
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_user
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int insert(SysManagerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_user
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int insertSelective(SysManagerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_user
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    List<SysManagerUser> selectByExample(SysManagerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_user
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    SysManagerUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_user
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysManagerUser record, @Param("example") SysManagerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_user
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int updateByExample(@Param("record") SysManagerUser record, @Param("example") SysManagerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_user
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int updateByPrimaryKeySelective(SysManagerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_user
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int updateByPrimaryKey(SysManagerUser record);
}