
package com.os.manager.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.os.manager.dbmodel.SysManagerUserArea;
import com.os.manager.dbmodel.SysManagerUserAreaExample;

public interface SysManagerUserAreaMapper
{
	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_area
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	long countByExample(SysManagerUserAreaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_area
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int deleteByExample(SysManagerUserAreaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_area
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_area
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int insert(SysManagerUserArea record);

	int insertList(@ Param (value = "list") List<SysManagerUserArea> records);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_area
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int insertSelective(SysManagerUserArea record);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_area
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	List<SysManagerUserArea> selectByExample(SysManagerUserAreaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_area
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	SysManagerUserArea selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_area
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int updateByExampleSelective(@ Param ("record") SysManagerUserArea record ,
		@ Param ("example") SysManagerUserAreaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_area
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int updateByExample(@ Param ("record") SysManagerUserArea record ,
		@ Param ("example") SysManagerUserAreaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_area
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int updateByPrimaryKeySelective(SysManagerUserArea record);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_area
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int updateByPrimaryKey(SysManagerUserArea record);
}
