package com.os.manager.dao;

import com.os.manager.dbmodel.SysManagerSupplierUser;
import com.os.manager.dbmodel.SysManagerSupplierUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysManagerSupplierUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_supplier_user
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    long countByExample(SysManagerSupplierUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_supplier_user
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    int deleteByExample(SysManagerSupplierUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_supplier_user
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_supplier_user
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    int insert(SysManagerSupplierUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_supplier_user
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    int insertSelective(SysManagerSupplierUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_supplier_user
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    List<SysManagerSupplierUser> selectByExample(SysManagerSupplierUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_supplier_user
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    SysManagerSupplierUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_supplier_user
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysManagerSupplierUser record, @Param("example") SysManagerSupplierUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_supplier_user
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    int updateByExample(@Param("record") SysManagerSupplierUser record, @Param("example") SysManagerSupplierUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_supplier_user
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    int updateByPrimaryKeySelective(SysManagerSupplierUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_supplier_user
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    int updateByPrimaryKey(SysManagerSupplierUser record);
}