
package com.os.manager.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.os.manager.dbmodel.SysManagerUserRepertory;
import com.os.manager.dbmodel.SysManagerUserRepertoryExample;

public interface SysManagerUserRepertoryMapper
{
	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_repertory
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	long countByExample(SysManagerUserRepertoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_repertory
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int deleteByExample(SysManagerUserRepertoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_repertory
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_repertory
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int insert(SysManagerUserRepertory record);

	int insertList(@ Param (value = "list") List<SysManagerUserRepertory> record);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_repertory
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int insertSelective(SysManagerUserRepertory record);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_repertory
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	List<SysManagerUserRepertory> selectByExample(SysManagerUserRepertoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_repertory
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	SysManagerUserRepertory selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_repertory
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int updateByExampleSelective(@ Param ("record") SysManagerUserRepertory record ,
		@ Param ("example") SysManagerUserRepertoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_repertory
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int updateByExample(@ Param ("record") SysManagerUserRepertory record ,
		@ Param ("example") SysManagerUserRepertoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_repertory
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int updateByPrimaryKeySelective(SysManagerUserRepertory record);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_repertory
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int updateByPrimaryKey(SysManagerUserRepertory record);
}
