package com.os.manager.dbmodel;

import java.util.Date;

public class SysConfigRolePrice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_role_price.id
     *
     * @mbg.generated Thu Jan 03 15:31:14 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_role_price.create_time
     *
     * @mbg.generated Thu Jan 03 15:31:14 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_role_price.modified_time
     *
     * @mbg.generated Thu Jan 03 15:31:14 CST 2019
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_role_price.role_id
     *
     * @mbg.generated Thu Jan 03 15:31:14 CST 2019
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_role_price.price_id
     *
     * @mbg.generated Thu Jan 03 15:31:14 CST 2019
     */
    private Long priceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_role_price.id
     *
     * @return the value of sys_config_role_price.id
     *
     * @mbg.generated Thu Jan 03 15:31:14 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_role_price.id
     *
     * @param id the value for sys_config_role_price.id
     *
     * @mbg.generated Thu Jan 03 15:31:14 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_role_price.create_time
     *
     * @return the value of sys_config_role_price.create_time
     *
     * @mbg.generated Thu Jan 03 15:31:14 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_role_price.create_time
     *
     * @param createTime the value for sys_config_role_price.create_time
     *
     * @mbg.generated Thu Jan 03 15:31:14 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_role_price.modified_time
     *
     * @return the value of sys_config_role_price.modified_time
     *
     * @mbg.generated Thu Jan 03 15:31:14 CST 2019
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_role_price.modified_time
     *
     * @param modifiedTime the value for sys_config_role_price.modified_time
     *
     * @mbg.generated Thu Jan 03 15:31:14 CST 2019
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_role_price.role_id
     *
     * @return the value of sys_config_role_price.role_id
     *
     * @mbg.generated Thu Jan 03 15:31:14 CST 2019
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_role_price.role_id
     *
     * @param roleId the value for sys_config_role_price.role_id
     *
     * @mbg.generated Thu Jan 03 15:31:14 CST 2019
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_role_price.price_id
     *
     * @return the value of sys_config_role_price.price_id
     *
     * @mbg.generated Thu Jan 03 15:31:14 CST 2019
     */
    public Long getPriceId() {
        return priceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_role_price.price_id
     *
     * @param priceId the value for sys_config_role_price.price_id
     *
     * @mbg.generated Thu Jan 03 15:31:14 CST 2019
     */
    public void setPriceId(Long priceId) {
        this.priceId = priceId;
    }
}