package com.os.manager.dbmodel;

import java.util.Date;

public class SysConfigAuths {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_auths.id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_auths.create_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_auths.modified_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_auths.auth_name
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private String authName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_auths.auth_desc
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private String authDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_auths.id
     *
     * @return the value of sys_config_auths.id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_auths.id
     *
     * @param id the value for sys_config_auths.id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_auths.create_time
     *
     * @return the value of sys_config_auths.create_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_auths.create_time
     *
     * @param createTime the value for sys_config_auths.create_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_auths.modified_time
     *
     * @return the value of sys_config_auths.modified_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_auths.modified_time
     *
     * @param modifiedTime the value for sys_config_auths.modified_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_auths.auth_name
     *
     * @return the value of sys_config_auths.auth_name
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public String getAuthName() {
        return authName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_auths.auth_name
     *
     * @param authName the value for sys_config_auths.auth_name
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setAuthName(String authName) {
        this.authName = authName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_auths.auth_desc
     *
     * @return the value of sys_config_auths.auth_desc
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public String getAuthDesc() {
        return authDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_auths.auth_desc
     *
     * @param authDesc the value for sys_config_auths.auth_desc
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setAuthDesc(String authDesc) {
        this.authDesc = authDesc;
    }
}