package com.os.manager.dbmodel;

import java.util.Date;

public class SysConfigRoleAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_role_auth.id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_role_auth.create_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_role_auth.modified_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_role_auth.role_id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_role_auth.auth_id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private Long authId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_role_auth.id
     *
     * @return the value of sys_config_role_auth.id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_role_auth.id
     *
     * @param id the value for sys_config_role_auth.id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_role_auth.create_time
     *
     * @return the value of sys_config_role_auth.create_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_role_auth.create_time
     *
     * @param createTime the value for sys_config_role_auth.create_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_role_auth.modified_time
     *
     * @return the value of sys_config_role_auth.modified_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_role_auth.modified_time
     *
     * @param modifiedTime the value for sys_config_role_auth.modified_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_role_auth.role_id
     *
     * @return the value of sys_config_role_auth.role_id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_role_auth.role_id
     *
     * @param roleId the value for sys_config_role_auth.role_id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_role_auth.auth_id
     *
     * @return the value of sys_config_role_auth.auth_id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public Long getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_role_auth.auth_id
     *
     * @param authId the value for sys_config_role_auth.auth_id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setAuthId(Long authId) {
        this.authId = authId;
    }
}