package com.os.manager.dbmodel;

import java.util.Date;

public class SysConfigBrand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_brand.id
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_brand.create_time
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_brand.modified_time
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_brand.brand_name
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_brand.show_index
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    private Integer showIndex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_brand.id
     *
     * @return the value of sys_config_brand.id
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_brand.id
     *
     * @param id the value for sys_config_brand.id
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_brand.create_time
     *
     * @return the value of sys_config_brand.create_time
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_brand.create_time
     *
     * @param createTime the value for sys_config_brand.create_time
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_brand.modified_time
     *
     * @return the value of sys_config_brand.modified_time
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_brand.modified_time
     *
     * @param modifiedTime the value for sys_config_brand.modified_time
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_brand.brand_name
     *
     * @return the value of sys_config_brand.brand_name
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_brand.brand_name
     *
     * @param brandName the value for sys_config_brand.brand_name
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_brand.show_index
     *
     * @return the value of sys_config_brand.show_index
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    public Integer getShowIndex() {
        return showIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_brand.show_index
     *
     * @param showIndex the value for sys_config_brand.show_index
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    public void setShowIndex(Integer showIndex) {
        this.showIndex = showIndex;
    }
}