package com.os.manager.dbmodel;

import java.util.Date;

public class SysConfigSettingType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_setting_type.id
     *
     * @mbg.generated Wed Jan 09 10:37:49 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_setting_type.create_time
     *
     * @mbg.generated Wed Jan 09 10:37:49 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_setting_type.modified_time
     *
     * @mbg.generated Wed Jan 09 10:37:49 CST 2019
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_setting_type.setting_name
     *
     * @mbg.generated Wed Jan 09 10:37:49 CST 2019
     */
    private String settingName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_setting_type.id
     *
     * @return the value of sys_config_setting_type.id
     *
     * @mbg.generated Wed Jan 09 10:37:49 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_setting_type.id
     *
     * @param id the value for sys_config_setting_type.id
     *
     * @mbg.generated Wed Jan 09 10:37:49 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_setting_type.create_time
     *
     * @return the value of sys_config_setting_type.create_time
     *
     * @mbg.generated Wed Jan 09 10:37:49 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_setting_type.create_time
     *
     * @param createTime the value for sys_config_setting_type.create_time
     *
     * @mbg.generated Wed Jan 09 10:37:49 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_setting_type.modified_time
     *
     * @return the value of sys_config_setting_type.modified_time
     *
     * @mbg.generated Wed Jan 09 10:37:49 CST 2019
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_setting_type.modified_time
     *
     * @param modifiedTime the value for sys_config_setting_type.modified_time
     *
     * @mbg.generated Wed Jan 09 10:37:49 CST 2019
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_setting_type.setting_name
     *
     * @return the value of sys_config_setting_type.setting_name
     *
     * @mbg.generated Wed Jan 09 10:37:49 CST 2019
     */
    public String getSettingName() {
        return settingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_setting_type.setting_name
     *
     * @param settingName the value for sys_config_setting_type.setting_name
     *
     * @mbg.generated Wed Jan 09 10:37:49 CST 2019
     */
    public void setSettingName(String settingName) {
        this.settingName = settingName;
    }
}