package com.os.manager.dbmodel;

import java.util.Date;

public class SysConfigSetting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_setting.id
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_setting.create_time
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_setting.modified_time
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_setting.setting_name
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    private String settingName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_setting.setting_desc
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    private String settingDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_setting.setting_value
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    private String settingValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_setting.setting_type
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    private Integer settingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_setting.setting_option
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    private String settingOption;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_setting.id
     *
     * @return the value of sys_config_setting.id
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_setting.id
     *
     * @param id the value for sys_config_setting.id
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_setting.create_time
     *
     * @return the value of sys_config_setting.create_time
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_setting.create_time
     *
     * @param createTime the value for sys_config_setting.create_time
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_setting.modified_time
     *
     * @return the value of sys_config_setting.modified_time
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_setting.modified_time
     *
     * @param modifiedTime the value for sys_config_setting.modified_time
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_setting.setting_name
     *
     * @return the value of sys_config_setting.setting_name
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    public String getSettingName() {
        return settingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_setting.setting_name
     *
     * @param settingName the value for sys_config_setting.setting_name
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    public void setSettingName(String settingName) {
        this.settingName = settingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_setting.setting_desc
     *
     * @return the value of sys_config_setting.setting_desc
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    public String getSettingDesc() {
        return settingDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_setting.setting_desc
     *
     * @param settingDesc the value for sys_config_setting.setting_desc
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    public void setSettingDesc(String settingDesc) {
        this.settingDesc = settingDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_setting.setting_value
     *
     * @return the value of sys_config_setting.setting_value
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    public String getSettingValue() {
        return settingValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_setting.setting_value
     *
     * @param settingValue the value for sys_config_setting.setting_value
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    public void setSettingValue(String settingValue) {
        this.settingValue = settingValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_setting.setting_type
     *
     * @return the value of sys_config_setting.setting_type
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    public Integer getSettingType() {
        return settingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_setting.setting_type
     *
     * @param settingType the value for sys_config_setting.setting_type
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    public void setSettingType(Integer settingType) {
        this.settingType = settingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_setting.setting_option
     *
     * @return the value of sys_config_setting.setting_option
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    public String getSettingOption() {
        return settingOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_setting.setting_option
     *
     * @param settingOption the value for sys_config_setting.setting_option
     *
     * @mbg.generated Thu Jan 10 09:28:23 CST 2019
     */
    public void setSettingOption(String settingOption) {
        this.settingOption = settingOption;
    }
}