package com.os.manager.dbmodel;

import java.util.Date;

public class SysManagerUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_user.id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_user.create_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_user.modified_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_user.role_id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_user.user_name
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_user.account_name
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_user.user_phone
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_user.status
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_user.id
     *
     * @return the value of sys_manager_user.id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_user.id
     *
     * @param id the value for sys_manager_user.id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_user.create_time
     *
     * @return the value of sys_manager_user.create_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_user.create_time
     *
     * @param createTime the value for sys_manager_user.create_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_user.modified_time
     *
     * @return the value of sys_manager_user.modified_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_user.modified_time
     *
     * @param modifiedTime the value for sys_manager_user.modified_time
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_user.role_id
     *
     * @return the value of sys_manager_user.role_id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_user.role_id
     *
     * @param roleId the value for sys_manager_user.role_id
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_user.user_name
     *
     * @return the value of sys_manager_user.user_name
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_user.user_name
     *
     * @param userName the value for sys_manager_user.user_name
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_user.account_name
     *
     * @return the value of sys_manager_user.account_name
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_user.account_name
     *
     * @param accountName the value for sys_manager_user.account_name
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_user.user_phone
     *
     * @return the value of sys_manager_user.user_phone
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_user.user_phone
     *
     * @param userPhone the value for sys_manager_user.user_phone
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_user.status
     *
     * @return the value of sys_manager_user.status
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_user.status
     *
     * @param status the value for sys_manager_user.status
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}