package com.os.manager.dbmodel;

import java.util.Date;

public class SysManagerSupplierUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier_user.id
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier_user.create_time
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier_user.modified_time
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier_user.manager_id
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    private String managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier_user.user_name
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier_user.user_sex
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    private Integer userSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier_user.birthday
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier_user.apartment
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    private String apartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier_user.role
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier_user.phone
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier_user.fax
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier_user.mobile_phone
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    private String mobilePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier_user.wechat
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    private String wechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier_user.user_email
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier_user.experience
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    private String experience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier_user.hobby
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    private String hobby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier_user.supplier_id
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    private Long supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_supplier_user.user_desc
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    private String userDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier_user.id
     *
     * @return the value of sys_manager_supplier_user.id
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier_user.id
     *
     * @param id the value for sys_manager_supplier_user.id
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier_user.create_time
     *
     * @return the value of sys_manager_supplier_user.create_time
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier_user.create_time
     *
     * @param createTime the value for sys_manager_supplier_user.create_time
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier_user.modified_time
     *
     * @return the value of sys_manager_supplier_user.modified_time
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier_user.modified_time
     *
     * @param modifiedTime the value for sys_manager_supplier_user.modified_time
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier_user.manager_id
     *
     * @return the value of sys_manager_supplier_user.manager_id
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier_user.manager_id
     *
     * @param managerId the value for sys_manager_supplier_user.manager_id
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier_user.user_name
     *
     * @return the value of sys_manager_supplier_user.user_name
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier_user.user_name
     *
     * @param userName the value for sys_manager_supplier_user.user_name
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier_user.user_sex
     *
     * @return the value of sys_manager_supplier_user.user_sex
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public Integer getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier_user.user_sex
     *
     * @param userSex the value for sys_manager_supplier_user.user_sex
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier_user.birthday
     *
     * @return the value of sys_manager_supplier_user.birthday
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier_user.birthday
     *
     * @param birthday the value for sys_manager_supplier_user.birthday
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier_user.apartment
     *
     * @return the value of sys_manager_supplier_user.apartment
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public String getApartment() {
        return apartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier_user.apartment
     *
     * @param apartment the value for sys_manager_supplier_user.apartment
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public void setApartment(String apartment) {
        this.apartment = apartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier_user.role
     *
     * @return the value of sys_manager_supplier_user.role
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier_user.role
     *
     * @param role the value for sys_manager_supplier_user.role
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier_user.phone
     *
     * @return the value of sys_manager_supplier_user.phone
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier_user.phone
     *
     * @param phone the value for sys_manager_supplier_user.phone
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier_user.fax
     *
     * @return the value of sys_manager_supplier_user.fax
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier_user.fax
     *
     * @param fax the value for sys_manager_supplier_user.fax
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier_user.mobile_phone
     *
     * @return the value of sys_manager_supplier_user.mobile_phone
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier_user.mobile_phone
     *
     * @param mobilePhone the value for sys_manager_supplier_user.mobile_phone
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier_user.wechat
     *
     * @return the value of sys_manager_supplier_user.wechat
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier_user.wechat
     *
     * @param wechat the value for sys_manager_supplier_user.wechat
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier_user.user_email
     *
     * @return the value of sys_manager_supplier_user.user_email
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier_user.user_email
     *
     * @param userEmail the value for sys_manager_supplier_user.user_email
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier_user.experience
     *
     * @return the value of sys_manager_supplier_user.experience
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public String getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier_user.experience
     *
     * @param experience the value for sys_manager_supplier_user.experience
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public void setExperience(String experience) {
        this.experience = experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier_user.hobby
     *
     * @return the value of sys_manager_supplier_user.hobby
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier_user.hobby
     *
     * @param hobby the value for sys_manager_supplier_user.hobby
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public void setHobby(String hobby) {
        this.hobby = hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier_user.supplier_id
     *
     * @return the value of sys_manager_supplier_user.supplier_id
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public Long getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier_user.supplier_id
     *
     * @param supplierId the value for sys_manager_supplier_user.supplier_id
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public void setSupplierId(Long supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_supplier_user.user_desc
     *
     * @return the value of sys_manager_supplier_user.user_desc
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public String getUserDesc() {
        return userDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_supplier_user.user_desc
     *
     * @param userDesc the value for sys_manager_supplier_user.user_desc
     *
     * @mbg.generated Tue Jan 15 14:26:42 CST 2019
     */
    public void setUserDesc(String userDesc) {
        this.userDesc = userDesc;
    }
}