package com.os.manager.dao;

import com.os.manager.dbmodel.SysConfigPrice;
import com.os.manager.dbmodel.SysConfigPriceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysConfigPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_price
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    long countByExample(SysConfigPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_price
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int deleteByExample(SysConfigPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_price
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_price
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int insert(SysConfigPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_price
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int insertSelective(SysConfigPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_price
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    List<SysConfigPrice> selectByExample(SysConfigPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_price
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    SysConfigPrice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_price
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysConfigPrice record, @Param("example") SysConfigPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_price
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int updateByExample(@Param("record") SysConfigPrice record, @Param("example") SysConfigPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_price
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int updateByPrimaryKeySelective(SysConfigPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_price
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int updateByPrimaryKey(SysConfigPrice record);
}