
package com.os.manager.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.os.manager.dbmodel.SysConfigRolePrice;
import com.os.manager.dbmodel.SysConfigRolePriceExample;

public interface SysConfigRolePriceMapper
{
	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_config_role_price
	 *
	 * @mbg.generated Thu Jan 03 15:31:14 CST 2019
	 */
	long countByExample(SysConfigRolePriceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_config_role_price
	 *
	 * @mbg.generated Thu Jan 03 15:31:14 CST 2019
	 */
	int deleteByExample(SysConfigRolePriceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_config_role_price
	 *
	 * @mbg.generated Thu Jan 03 15:31:14 CST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_config_role_price
	 *
	 * @mbg.generated Thu Jan 03 15:31:14 CST 2019
	 */
	int insert(SysConfigRolePrice record);

	/**
	 * 批量添加
	 * @param record
	 * @return
	 */
	int insertList(@ Param (value = "list") List<SysConfigRolePrice> records);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_config_role_price
	 *
	 * @mbg.generated Thu Jan 03 15:31:14 CST 2019
	 */
	int insertSelective(SysConfigRolePrice record);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_config_role_price
	 *
	 * @mbg.generated Thu Jan 03 15:31:14 CST 2019
	 */
	List<SysConfigRolePrice> selectByExample(SysConfigRolePriceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_config_role_price
	 *
	 * @mbg.generated Thu Jan 03 15:31:14 CST 2019
	 */
	SysConfigRolePrice selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_config_role_price
	 *
	 * @mbg.generated Thu Jan 03 15:31:14 CST 2019
	 */
	int updateByExampleSelective(@ Param ("record") SysConfigRolePrice record ,
		@ Param ("example") SysConfigRolePriceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_config_role_price
	 *
	 * @mbg.generated Thu Jan 03 15:31:14 CST 2019
	 */
	int updateByExample(@ Param ("record") SysConfigRolePrice record ,
		@ Param ("example") SysConfigRolePriceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_config_role_price
	 *
	 * @mbg.generated Thu Jan 03 15:31:14 CST 2019
	 */
	int updateByPrimaryKeySelective(SysConfigRolePrice record);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_config_role_price
	 *
	 * @mbg.generated Thu Jan 03 15:31:14 CST 2019
	 */
	int updateByPrimaryKey(SysConfigRolePrice record);
}
