package com.os.manager.dao;

import com.os.manager.dbmodel.SysConfigSettingOption;
import com.os.manager.dbmodel.SysConfigSettingOptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysConfigSettingOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    long countByExample(SysConfigSettingOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    int deleteByExample(SysConfigSettingOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    int insert(SysConfigSettingOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    int insertSelective(SysConfigSettingOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    List<SysConfigSettingOption> selectByExample(SysConfigSettingOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    SysConfigSettingOption selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysConfigSettingOption record, @Param("example") SysConfigSettingOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    int updateByExample(@Param("record") SysConfigSettingOption record, @Param("example") SysConfigSettingOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    int updateByPrimaryKeySelective(SysConfigSettingOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_setting_option
     *
     * @mbg.generated Wed Jan 09 13:49:39 CST 2019
     */
    int updateByPrimaryKey(SysConfigSettingOption record);
}