package com.os.manager.dao;

import com.os.manager.dbmodel.SysConfigArea;
import com.os.manager.dbmodel.SysConfigAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysConfigAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_area
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    long countByExample(SysConfigAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_area
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    int deleteByExample(SysConfigAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_area
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_area
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    int insert(SysConfigArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_area
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    int insertSelective(SysConfigArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_area
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    List<SysConfigArea> selectByExample(SysConfigAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_area
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    SysConfigArea selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_area
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysConfigArea record, @Param("example") SysConfigAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_area
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    int updateByExample(@Param("record") SysConfigArea record, @Param("example") SysConfigAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_area
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    int updateByPrimaryKeySelective(SysConfigArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_area
     *
     * @mbg.generated Sat Jan 05 21:19:17 CST 2019
     */
    int updateByPrimaryKey(SysConfigArea record);
}