package com.os.manager.dao;

import com.os.manager.dbmodel.SysConfigRoles;
import com.os.manager.dbmodel.SysConfigRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysConfigRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_roles
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    long countByExample(SysConfigRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_roles
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int deleteByExample(SysConfigRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_roles
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_roles
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int insert(SysConfigRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_roles
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int insertSelective(SysConfigRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_roles
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    List<SysConfigRoles> selectByExample(SysConfigRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_roles
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    SysConfigRoles selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_roles
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysConfigRoles record, @Param("example") SysConfigRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_roles
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int updateByExample(@Param("record") SysConfigRoles record, @Param("example") SysConfigRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_roles
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int updateByPrimaryKeySelective(SysConfigRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_roles
     *
     * @mbg.generated Sun Dec 30 20:58:22 CST 2018
     */
    int updateByPrimaryKey(SysConfigRoles record);
}