
package com.os.manager.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.os.manager.dbmodel.SysManagerUserBrand;
import com.os.manager.dbmodel.SysManagerUserBrandExample;

public interface SysManagerUserBrandMapper
{
	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_brand
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	long countByExample(SysManagerUserBrandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_brand
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int deleteByExample(SysManagerUserBrandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_brand
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_brand
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int insert(SysManagerUserBrand record);

	int insertList(@ Param (value = "list") List<SysManagerUserBrand> brands);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_brand
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int insertSelective(SysManagerUserBrand record);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_brand
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	List<SysManagerUserBrand> selectByExample(SysManagerUserBrandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_brand
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	SysManagerUserBrand selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_brand
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int updateByExampleSelective(@ Param ("record") SysManagerUserBrand record ,
		@ Param ("example") SysManagerUserBrandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_brand
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int updateByExample(@ Param ("record") SysManagerUserBrand record ,
		@ Param ("example") SysManagerUserBrandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_brand
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int updateByPrimaryKeySelective(SysManagerUserBrand record);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_brand
	 *
	 * @mbg.generated Tue Jan 08 11:46:59 CST 2019
	 */
	int updateByPrimaryKey(SysManagerUserBrand record);
}
