
package com.os.manager.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.os.manager.dbmodel.SysManagerUser;
import com.os.manager.dbmodel.SysManagerUserExample;

public interface SysManagerUserMapper
{
	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	long countByExample(SysManagerUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	int deleteByExample(SysManagerUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	int insert(SysManagerUser record);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	int insertSelective(SysManagerUser record);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	List<SysManagerUser> selectByExample(SysManagerUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	SysManagerUser selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	int updateByExampleSelective(@ Param ("record") SysManagerUser record ,
		@ Param ("example") SysManagerUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	int updateByExample(@ Param ("record") SysManagerUser record ,
		@ Param ("example") SysManagerUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	int updateByPrimaryKeySelective(SysManagerUser record);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user
	 *
	 * @mbg.generated Tue Jan 08 09:41:24 CST 2019
	 */
	int updateByPrimaryKey(SysManagerUser record);

	int updateBaseInfoByPrimaryKey(SysManagerUser record);
}
