
package com.os.manager.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.os.manager.dbmodel.SysManagerUserRole;
import com.os.manager.dbmodel.SysManagerUserRoleExample;

public interface SysManagerUserRoleMapper
{
	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_role
	 *
	 * @mbg.generated Tue Jan 08 16:35:04 CST 2019
	 */
	long countByExample(SysManagerUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_role
	 *
	 * @mbg.generated Tue Jan 08 16:35:04 CST 2019
	 */
	int deleteByExample(SysManagerUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_role
	 *
	 * @mbg.generated Tue Jan 08 16:35:04 CST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_role
	 *
	 * @mbg.generated Tue Jan 08 16:35:04 CST 2019
	 */
	int insert(SysManagerUserRole record);

	int insertList(@ Param (value = "list") List<SysManagerUserRole> records);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_role
	 *
	 * @mbg.generated Tue Jan 08 16:35:04 CST 2019
	 */
	int insertSelective(SysManagerUserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_role
	 *
	 * @mbg.generated Tue Jan 08 16:35:04 CST 2019
	 */
	List<SysManagerUserRole> selectByExample(SysManagerUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_role
	 *
	 * @mbg.generated Tue Jan 08 16:35:04 CST 2019
	 */
	SysManagerUserRole selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_role
	 *
	 * @mbg.generated Tue Jan 08 16:35:04 CST 2019
	 */
	int updateByExampleSelective(@ Param ("record") SysManagerUserRole record ,
		@ Param ("example") SysManagerUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_role
	 *
	 * @mbg.generated Tue Jan 08 16:35:04 CST 2019
	 */
	int updateByExample(@ Param ("record") SysManagerUserRole record ,
		@ Param ("example") SysManagerUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_role
	 *
	 * @mbg.generated Tue Jan 08 16:35:04 CST 2019
	 */
	int updateByPrimaryKeySelective(SysManagerUserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_manager_user_role
	 *
	 * @mbg.generated Tue Jan 08 16:35:04 CST 2019
	 */
	int updateByPrimaryKey(SysManagerUserRole record);
}
